SELECT 
CASE 
WHEN BIRTHDAY LIKE (SELECT MAX(BIRTHDAY) FROM WORKER )THEN 'YOUNGEST'
WHEN BIRTHDAY LIKE(SELECT MIN(BIRTHDAY) FROM WORKER) THEN 'ELDEST'
END AS TYPE ,
NAME,
BIRTHDAY
FROM WORKER
WHERE  BIRTHDAY LIKE (SELECT MAX(BIRTHDAY) FROM WORKER ) OR  BIRTHDAY LIKE (SELECT MIN(BIRTHDAY) FROM WORKER )
