
CREATE TABLE WORKER(
ID BIGINT  PRIMARY KEY,
NAME VARCHAR NOT NULL CHECK( CHAR_LENGTH (NAME) >1 AND CHAR_LENGTH (NAME) <1000  ),
BIRTHDAY DATE  CHECK(YEAR(BIRTHDAY) >1900) ,
LEVER VARCHAR(7) NOT NULL,
SALARY BIGINT CHECK (SALARY BETWEEN 100 AND 100000)
);

CREATE TABLE CLIENT (
ID BIGINT  PRIMARY KEY,
NAME VARCHAR NOT NULL  CHECK( CHAR_LENGTH (NAME) >1 AND CHAR_LENGTH (NAME) <1000  )
);

CREATE TABLE PROJECT (
ID BIGINT  PRIMARY KEY,
CLIENT_ID BIGINT,
START_DATE  DATE,
FINISH_DATE  DATE,
FOREIGN KEY(CLIENT_ID)
REFERENCES CLIENT(ID)
);

CREATE TABLE PROJECT_WORKER (
PROJECT_ID BIGINT ,
WORKER_ID BIGINT,
PRIMARY KEY (PROJECT_ID,WORKER_ID),
FOREIGN KEY(project_id) REFERENCES project(id),
FOREIGN KEY(WORKER_id) REFERENCES WORKER(id)
);

