SELECT
PROJECT_ID,
((SELECT DATEDIFF(MONTH,START_DATE,FINISH_DATE) FROM PROJECT WHERE ID = PROJECT_ID )
*
SUM(SELECT SALARY FROM WORKER WHERE ID = WORKER_ID)
)AS PRICE

FROM PROJECT_WORKER
GROUP BY PROJECT_ID
ORDER BY PRICE DESC